services:
  db1:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Strong@Password"
      ACCEPT_EULA: "Y"
  edi315api:
    build:
      context: .
      dockerfile: EDI315Api/Dockerfile
    container_name: edi315api
    ports:
      - "3001:3001"
    depends_on:
      - db1
  edi315payment:
    build:
      context: .
      dockerfile: EDI315Payment/Dockerfile
    container_name: edi315payment
    ports:
      - "4000:8080"  
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
   
      
