services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    container_name: cosmosdb
    ports:
      - "8082:8081" 
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=5
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
  db1:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Strong@Password"
      ACCEPT_EULA: "Y"
  edi315api:
    build:
      context: .
      dockerfile: EDI315Api/Dockerfile
    container_name: edi315api
    ports:
      - "3000:8080"
    depends_on:
      - db1
      - cosmosdb
